"""Persistent catalogue for files generated by Agent World.

Only relative storage paths are exposed to the storage service.  Absolute
roots and authentication hashes are deliberately omitted from serialized API
representations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from .base import BaseModel, db


class SharePermission(str, Enum):
    """Capabilities granted by a file share link."""

    READ = "read"
    WRITE = "write"


class GeneratedFile(BaseModel):
    """A logical generated file whose physical versions are append-only."""

    __tablename__ = "generated_files"
    __table_args__ = (
        db.UniqueConstraint(
            "agent_id", "logical_name", name="uq_generated_file_agent_name"
        ),
    )

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    agent_id = db.Column(
        db.Integer, db.ForeignKey("agents.id", ondelete="CASCADE"), nullable=False
    )
    execution_id = db.Column(
        db.Integer, db.ForeignKey("executions.id", ondelete="SET NULL"), nullable=True
    )
    created_by = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    logical_name = db.Column(db.String(255), nullable=False)
    file_format = db.Column(db.String(16), nullable=False)
    mime_type = db.Column(db.String(100), nullable=False)
    storage_key = db.Column(db.String(36), nullable=False, unique=True, index=True)
    storage_root = db.Column(db.Text, nullable=False)
    current_version = db.Column(db.Integer, nullable=False, default=1)
    size_bytes = db.Column(db.Integer, nullable=False, default=0)
    sha256 = db.Column(db.String(64), nullable=False)
    management_token_hash = db.Column(
        db.String(64), nullable=False, unique=True, index=True
    )
    is_temporary = db.Column(db.Boolean, nullable=False, default=False)
    pinned = db.Column(db.Boolean, nullable=False, default=False)
    expires_at = db.Column(db.DateTime, nullable=True)
    last_accessed_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    agent = db.relationship("Agent", foreign_keys=[agent_id])
    execution = db.relationship("Execution", foreign_keys=[execution_id])
    creator = db.relationship("User", foreign_keys=[created_by])
    versions = db.relationship(
        "FileVersion",
        back_populates="generated_file",
        cascade="all, delete-orphan",
        order_by="FileVersion.version",
    )
    shares = db.relationship(
        "FileShare",
        back_populates="generated_file",
        cascade="all, delete-orphan",
    )

    def to_dict(self) -> dict[str, Any]:
        """Return public metadata without local paths or secret hashes."""

        return {
            "id": self.id,
            "agent_id": self.agent_id,
            "execution_id": self.execution_id,
            "created_by": self.created_by,
            "name": self.logical_name,
            "format": self.file_format,
            "mime_type": self.mime_type,
            "current_version": self.current_version,
            "size_bytes": self.size_bytes,
            "sha256": self.sha256,
            "is_temporary": self.is_temporary,
            "pinned": self.pinned,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "last_accessed_at": (
                self.last_accessed_at.isoformat() if self.last_accessed_at else None
            ),
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    @classmethod
    def get_by_id(cls, file_id: int) -> "GeneratedFile | None":
        """Return a generated file by identifier."""

        return db.session.get(cls, file_id)


class FileVersion(BaseModel):
    """Immutable metadata for one physical version of a generated file."""

    __tablename__ = "file_versions"
    __table_args__ = (
        db.UniqueConstraint(
            "generated_file_id", "version", name="uq_file_version_number"
        ),
        db.UniqueConstraint(
            "generated_file_id", "relative_path", name="uq_file_version_path"
        ),
    )

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    generated_file_id = db.Column(
        db.Integer,
        db.ForeignKey("generated_files.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    version = db.Column(db.Integer, nullable=False)
    relative_path = db.Column(db.String(1024), nullable=False)
    size_bytes = db.Column(db.Integer, nullable=False)
    sha256 = db.Column(db.String(64), nullable=False)
    created_by = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    execution_id = db.Column(
        db.Integer, db.ForeignKey("executions.id", ondelete="SET NULL"), nullable=True
    )
    restored_from_version_id = db.Column(
        db.Integer,
        db.ForeignKey("file_versions.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    generated_file = db.relationship("GeneratedFile", back_populates="versions")
    creator = db.relationship("User", foreign_keys=[created_by])
    execution = db.relationship("Execution", foreign_keys=[execution_id])
    restored_from = db.relationship(
        "FileVersion", remote_side=[id], foreign_keys=[restored_from_version_id]
    )

    def to_dict(self) -> dict[str, Any]:
        """Return version metadata without its physical path."""

        return {
            "id": self.id,
            "file_id": self.generated_file_id,
            "version": self.version,
            "size_bytes": self.size_bytes,
            "sha256": self.sha256,
            "created_by": self.created_by,
            "execution_id": self.execution_id,
            "restored_from_version_id": self.restored_from_version_id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class FileShare(BaseModel):
    """Revocable, expiring capability link for a logical file."""

    __tablename__ = "file_shares"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    generated_file_id = db.Column(
        db.Integer,
        db.ForeignKey("generated_files.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    created_by = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    recipient_user_id = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=True
    )
    permission = db.Column(db.String(8), nullable=False)
    token_hash = db.Column(db.String(64), nullable=False, unique=True, index=True)
    expires_at = db.Column(db.DateTime, nullable=False)
    revoked_at = db.Column(db.DateTime, nullable=True)
    last_accessed_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    generated_file = db.relationship("GeneratedFile", back_populates="shares")
    creator = db.relationship("User", foreign_keys=[created_by])
    recipient = db.relationship("User", foreign_keys=[recipient_user_id])

    @property
    def is_revoked(self) -> bool:
        """Whether this capability has been explicitly revoked."""

        return self.revoked_at is not None

    def to_dict(self) -> dict[str, Any]:
        """Return share metadata without its token hash."""

        return {
            "id": self.id,
            "file_id": self.generated_file_id,
            "permission": self.permission,
            "created_by": self.created_by,
            "recipient_user_id": self.recipient_user_id,
            "expires_at": self.expires_at.isoformat(),
            "revoked_at": self.revoked_at.isoformat() if self.revoked_at else None,
            "last_accessed_at": (
                self.last_accessed_at.isoformat() if self.last_accessed_at else None
            ),
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
